name: Python package

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.0", "3.1", "3.2", "3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version for testing purposes
        run: python -c "import sys; print(sys.version)"
      - name: Run unittests
        run: |
          python unittest_runner.py
      - name: Run unittests directly
        run: |
          python -m unittest discover -s 'UnitTests' -p '*Tests.py'
